In [1]:
print("hello")


hello


In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3])

In [4]:
a

array([1, 2, 3])

In [5]:
z=np.zeros((2,3))

In [6]:
z

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
r=np.arange(0,10,2)

In [8]:
r

array([0, 2, 4, 6, 8])

In [9]:
b=np.array([4,5,6])

In [10]:
a+b

array([5, 7, 9])

In [11]:
np.mean(a)

np.float64(2.0)

In [12]:
np.max(a)

np.int32(3)

In [15]:
c=np.array([
    [1,2],
    [3,4]
])

In [16]:
c

array([[1, 2],
       [3, 4]])

In [17]:
d=np.array([
    [4,8],
    [6,9]
])

In [18]:
c+d

array([[ 5, 10],
       [ 9, 13]])

In [19]:
c*d

array([[ 4, 16],
       [18, 36]])

In [20]:
a*b

array([ 4, 10, 18])

In [21]:
f=np.dot(c,d)
f

array([[16, 26],
       [36, 60]])

In [23]:
f.T

array([[16, 36],
       [26, 60]])

In [24]:
 print("\n Matrix 1:\n",c)
 print("\n Matrix 2:\n",d)
 print("\n Addition :\n",c+d)
 print("\n Multiplication :\n",c*d)
 print("\n DOT multiplication rowX column :\n",f)
 print("\n Transpose :\n",f.T)


 Matrix 1:
 [[1 2]
 [3 4]]

 Matrix 2:
 [[4 8]
 [6 9]]

 Addition :
 [[ 5 10]
 [ 9 13]]

 Multiplication :
 [[ 4 16]
 [18 36]]

 DOT multiplication rowX column :
 [[16 26]
 [36 60]]

 Transpose :
 [[16 36]
 [26 60]]
